name: linux

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * SAT'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/aidasoft/centos7:latest
        volumes:
          - /cvmfs:/cvmfs:shared
        options: --privileged
    strategy:
      fail-fast: false
      matrix:
        SETUP: ['/cvmfs/sw.hsf.org/key4hep/setup.sh', '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
    steps:
    - uses: actions/checkout@v2
    - uses: vvolkl/github-action-cvmfs@centos7
      with:
        run_local_checkout: true
    - run: |
         mkdir -p build install
         git submodule init
         git submodule update
         source ${{ matrix.SETUP }}
         cd build
         cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=17  -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " -G Ninja ..;
